### ISSUE TITLE
PowerPoint ShapeProperties does not show a:xfrm (Transform2D)

### ISSUE THREAD

**Issue by raymrdc** [rmboggs/DocxToSource#3]
Powerpoint slide with shapes

Transform2D of shapes is generated when viewed from shapetree node (parent) but Transform2D values is not not shown when viewed from shapes node (child of shapetree).

Transform2D contains the Offset and Extents.

**Comment by rmboggs** [comment]
I haven't seen/noticed this issue when examining pptx files before.  I'll see if I can check it out tomorrow. 

Fyi - this issue might belong in the [Serialize.OpenXml.CodeGen](https://github.com/rmboggs/Serialize.OpenXml.CodeGen) project depending on where the issue is so don't be surprised if I move it there after I look into it.

**Comment by rmboggs** [comment]
I'm marking this as needs confirmation.  Meaning that I need to duplicate the issue on my side so I know how to fix.

**Comment by rmboggs** [comment]
Hi,
What values are you not seeing for the Transform2D element?  I just tried it and I am able to see the expected Offset and Extents properties just fine.  And off the top of my head, I don't recall any properties on the Transform2D element directly that are used often, if at all.  Please let me know.

**Comment by raymrdc** [comment]
Cosing this issue. I can't find the error now either. Must have look at the wrong shape when I reported this.
